baseURL = "https://music.nickcortale.com/"
locale = "en-us"
title = "Nicks Music"

[params]
  description = "A directory of artists."

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  genre = "genres"

